# Generated by Django 3.1 on 2020-08-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('name', models.TextField(blank=True, null=True, unique=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(null=True)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
    ]
